brew update
brew install ant
brew install icu4c
brew install libtool
brew install pcre
brew install sphinx-doc
brew install autoconf
brew install ideviceinstaller
brew install libusb
brew install pkg-config
brew install sqlite
brew install automake
brew install imagemagick
brew install libxml2
brew install pwgen
brew install sysbench
brew install bat
brew install ios-deploy
brew install libzip
brew install python
brew install telnet
brew install buck
brew install jpeg
brew install lumo
brew install python3
brew install tree
brew install cocoapods
brew install leiningen
brew install maven
brew install python@2
brew install usbmuxd
brew install expect
brew install libimobiledevice
brew install micro
brew install readline
brew install watchman
brew install freetype
brew install libplist
brew install mongodb
brew install redis
brew install xz
brew install gdbm
brew install libpng
brew install mysql
brew install rethinkdb
brew install yarn
brew install htop
brew install libtasn1
brew install node
brew install rlwrap
brew install hugo
brew install libtiff
brew install openssl
brew install sbt
